import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminMainLayout({ children }) {
  return (
    <html>
      <body>
        <NextAuthProvider>
          <main>
            <div className="flex">
              {/* <Sidebar /> */}
              {children}
            </div>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
