import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page({ children }) {
  return (
    <div className="min-h-screen">
      <h1>ADMIN PAGE HERE!</h1>
    </div>
  );
}
